# Generated by Django 5.1.4 on 2026-06-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('buy_time', models.DateTimeField(auto_now_add=True)),
                ('sell_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['-buy_time'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.CharField(blank=True, default='', max_length=16)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='trading_mar_symbol_a691f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('news_summary', models.TextField(blank=True, default='')),
                ('news_sentiment', models.FloatField(default=0.0)),
                ('reddit_summary', models.TextField(blank=True, default='')),
                ('reddit_sentiment', models.FloatField(default=0.0)),
                ('overall_sentiment', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='trading_sen_symbol_5926a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=4)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('agent_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='trading.trade')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
